package com.example.entity;


import static javax.persistence.GenerationType.IDENTITY;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/**
* Country generated by hbm2java
*/
@EqualsAndHashCode(exclude = {"citys","modifiedBy","modified","createdBy","created"})
@SuppressWarnings("serial")
@Entity
@Table(name = "Country", catalog = "demo_db")
public class Country implements java.io.Serializable {

 private Integer id;
 private String name;
 private int displayOrder;
 private int status;
 private String a2;
 private String a3;
 private int numericCode;
 private byte active;
 private Date created;
 private String createdBy;
 private Date modified;
 private String modifiedBy;
 @ToString.Exclude
 private Set<City> citys = new HashSet<City>(0);

 @Id
 @GeneratedValue(strategy = IDENTITY)

 @Column(name = "id", unique = true, nullable = false)
 public Integer getId() {
     return this.id;
 }

 public void setId(Integer id) {
     this.id = id;
 }

 @Column(name = "name", nullable = false)
 public String getName() {
     return this.name;
 }

 public void setName(String name) {
     this.name = name;
 }

 @Column(name = "display_order", nullable = false)
 public int getDisplayOrder() {
     return this.displayOrder;
 }

 public void setDisplayOrder(int displayOrder) {
     this.displayOrder = displayOrder;
 }

 @Column(name = "status", nullable = false)
 public int getStatus() {
     return this.status;
 }

 public void setStatus(int status) {
     this.status = status;
 }

 @Column(name = "a2", nullable = false, length = 2)
 public String getA2() {
     return this.a2;
 }

 public void setA2(String a2) {
     this.a2 = a2;
 }

 @Column(name = "a3", nullable = false)
 public String getA3() {
     return this.a3;
 }

 public void setA3(String a3) {
     this.a3 = a3;
 }

 @Column(name = "numeric_code", nullable = false)
 public int getNumericCode() {
     return this.numericCode;
 }

 public void setNumericCode(int numericCode) {
     this.numericCode = numericCode;
 }

 @Column(name = "active", nullable = false)
 public byte getActive() {
     return this.active;
 }

 public void setActive(byte active) {
     this.active = active;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name = "created", nullable = false, length = 19)
 public Date getCreated() {
     return this.created;
 }

 public void setCreated(Date created) {
     this.created = created;
 }

 @Column(name = "created_by", nullable = false)
 public String getCreatedBy() {
     return this.createdBy;
 }

 public void setCreatedBy(String createdBy) {
     this.createdBy = createdBy;
 }

 @Temporal(TemporalType.TIMESTAMP)
 @Column(name = "modified", length = 19)
 public Date getModified() {
     return this.modified;
 }

 public void setModified(Date modified) {
     this.modified = modified;
 }

 @Column(name = "modified_by")
 public String getModifiedBy() {
     return this.modifiedBy;
 }

 public void setModifiedBy(String modifiedBy) {
     this.modifiedBy = modifiedBy;
 }

 @OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
 public Set<City> getCitys() {
     return this.citys;
 }

 public void setCitys(Set<City> citys) {
     this.citys = citys;
 }

}

